# Generated by Django 5.0.8 on 2024-08-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
