# Generated by Django 5.0.8 on 2024-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_airplane_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="flights", to="airport.crew"
            ),
        ),
    ]
